const SELECTED: any[] = [
  {
    "id": "printful-fitness-1",
    "sku": "PFL-FIT-HOODIE-OUTDOOR",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Outdoor Club Zip Hoodie",
    "category": "Apparel",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 49.9,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-2",
    "sku": "PFL-FIT-HOODIE-TRAIL",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Trail Ready Zip Hoodie",
    "category": "Apparel",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 52.9,
    "image": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-3",
    "sku": "PFL-FIT-HOODIE-PR",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "PR Mode Zip Hoodie",
    "category": "Training",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 51.5,
    "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-4",
    "sku": "PFL-FIT-TEE-TRAIL",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Trail Ready Unisex Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 29.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-5",
    "sku": "PFL-FIT-TEE-LEGS",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Never Skip Leg Day Tee",
    "category": "Training",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.5,
    "image": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-6",
    "sku": "PFL-FIT-TEE-FJELL",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Fjell Runner Soft Tee",
    "category": "Outdoor",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-7",
    "sku": "PFL-FIT-CREW-SUNRISE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Sunrise Session Crewneck",
    "category": "Apparel",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 44.9,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-8",
    "sku": "PFL-FIT-CREW-MILES",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Nordic Miles Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 46.9,
    "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-9",
    "sku": "PFL-FIT-TEE-PLUNGE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Cold Plunge Club Tee",
    "category": "Training",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.9,
    "image": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-10",
    "sku": "PFL-FIT-HOODIE-SUMMIT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Summit Seekers Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 54.9,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-11",
    "sku": "PFL-FIT-CREW-RECOVERY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Recovery Day Crewneck",
    "category": "Training",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 43.9,
    "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-12",
    "sku": "PFL-FIT-TEE-HYDRATE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Hydrate & Elevate Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 25.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-13",
    "sku": "PFL-FIT-HOODIE-BASE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Base Camp Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 53.9,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-14",
    "sku": "PFL-FIT-TEE-TEMPO",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Tempo Run Soft Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-15",
    "sku": "PFL-FIT-CREW-FJORD",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Fjord Miles Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 45.9,
    "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-16",
    "sku": "PFL-FIT-HOODIE-ALT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Altitude Club Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 54.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-17",
    "sku": "PFL-FIT-TEE-MORNING",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Morning Miles Soft Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-18",
    "sku": "PFL-FIT-CREW-COLD",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Cold Air Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 46.5,
    "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-19",
    "sku": "PFL-FIT-HOODIE-PEAK",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Peak Season Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 55.9,
    "image": "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-20",
    "sku": "PFL-FIT-TEE-SWEAT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Sweat Equity Soft Tee",
    "category": "Training",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.5,
    "image": "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-21",
    "sku": "PFL-FIT-CREW-RIDGE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Ridge Line Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 47.9,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-22",
    "sku": "PFL-FIT-HOODIE-CROSS",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Nordic Cross Zip Hoodie",
    "category": "Apparel",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 52.9,
    "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-23",
    "sku": "PFL-FIT-TEE-PACE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Push Pace Soft Tee",
    "category": "Training",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.5,
    "image": "https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-24",
    "sku": "PFL-FIT-CREW-FOREST",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Forest Loop Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 45.5,
    "image": "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-25",
    "sku": "PFL-FIT-TEE-LASTREP",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Last Rep Soft Tee",
    "category": "Training",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 29.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch"
  },
  {
    "id": "printful-fitness-26",
    "sku": "PFL-FIT-HOODIE-SUMMIT2",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Summit Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 54.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-27",
    "sku": "PFL-FIT-TEE-STEADY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Steady Pace Soft Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-28",
    "sku": "PFL-FIT-CREW-DAWN",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Dawn Trail Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 46.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-29",
    "sku": "PFL-FIT-HOODIE-RIDGE2",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Ridge Soft Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 55.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-30",
    "sku": "PFL-FIT-TEE-MOVE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Move Soft Daily Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-31",
    "sku": "PFL-FIT-CREW-LAKE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Lake Loop Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 47.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-32",
    "sku": "PFL-FIT-HOODIE-WIND",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Wind Soft Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 53.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-33",
    "sku": "PFL-FIT-TEE-EASY",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Easy Miles Soft Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-34",
    "sku": "PFL-FIT-CREW-TERRAIN",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Terrain Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 45.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-35",
    "sku": "PFL-FIT-HOODIE-PATH",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Nordic Path Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 56.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-36",
    "sku": "PFL-FIT-TEE-FRESH",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Fresh Air Soft Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 29.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-37",
    "sku": "PFL-FIT-CREW-CABIN",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Cabin Run Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 48.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-38",
    "sku": "PFL-FIT-HOODIE-CLIMB",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Climb Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 52.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-39",
    "sku": "PFL-FIT-TEE-WALK",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Long Walk Soft Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 25.5,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-40",
    "sku": "PFL-FIT-CREW-MIST",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Mist Morning Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 44.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-41",
    "sku": "PFL-FIT-HOODIE-TRAILSOFT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Trail Soft Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 57.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-42",
    "sku": "PFL-FIT-TEE-STRONG",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Strong Soft Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 28.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-43",
    "sku": "PFL-FIT-CREW-PINE",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Pine Ridge Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 49.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-44",
    "sku": "PFL-FIT-HOODIE-OPEN",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Open Road Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 54.9,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-45",
    "sku": "PFL-FIT-TEE-PROGRESS",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Progress Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 27.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-46",
    "sku": "PFL-FIT-CREW-HARBOR",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Harbor Run Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 46.9,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-47",
    "sku": "PFL-FIT-HOODIE-ASCENT",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Ascent Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 55.9,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-48",
    "sku": "PFL-FIT-TEE-CLEAR",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Clear Day Soft Tee",
    "category": "Apparel",
    "supplierPriceUsd": 9.4,
    "suggestedRetailUsd": 26.9,
    "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=800&q=80",
    "matchType": "tee",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-49",
    "sku": "PFL-FIT-CREW-HORIZON",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Soft Horizon Crewneck",
    "category": "Outdoor",
    "supplierPriceUsd": 16.5,
    "suggestedRetailUsd": 47.9,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "crewneck",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  },
  {
    "id": "printful-fitness-50",
    "sku": "PFL-FIT-HOODIE-MILES2",
    "supplier": "Printful",
    "provider": "printful",
    "printifyProductId": "",
    "printifyVariantId": "",
    "name": "Nordic Miles Zip Hoodie",
    "category": "Outdoor",
    "supplierPriceUsd": 18.5,
    "suggestedRetailUsd": 58.5,
    "image": "https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=800&q=80",
    "matchType": "hoodie",
    "sector": "fitness",
    "compliance": "EU/Nordic POD merch only \u2014 apparel/poster/mug/tote/case/cap; no cosmetics liquids, no toy CE claims, no health claims"
  }
];
const SECTOR_ALIASES: Record<string, string> = {
  "beauty": "beauty",
  "perfume": "beauty",
  "perfumes": "beauty",
  "skincare": "beauty",
  "toys": "toys",
  "kids": "toys",
  "kid": "toys",
  "children": "toys",
  "electronics": "electronics",
  "tech": "electronics",
  "technology": "electronics",
  "pet supplies": "pet supplies",
  "pets": "pet supplies",
  "pet": "pet supplies",
  "home living": "home living",
  "home": "home living",
  "living": "home living",
  "fitness": "fitness",
  "outdoor": "fitness",
  "sports": "fitness",
  "solar energy": "solar energy",
  "energy": "solar energy",
  "solar": "solar energy",
  "car accessories": "car accessories",
  "car": "car accessories",
  "auto": "car accessories",
  "automotive": "car accessories"
};
function money(value: unknown) {
  const amount = Number(value);
  return Number.isFinite(amount) && amount > 0 ? Math.round(amount * 100) / 100 : 0;
}
function resolveSector(raw: string) {
  const key = String(raw || "").toLowerCase().trim();
  if (!key) return SELECTED[0]?.sector || "beauty";
  if (SECTOR_ALIASES[key]) return SECTOR_ALIASES[key];
  for (const [alias, sector] of Object.entries(SECTOR_ALIASES)) {
    if (key.includes(alias) || alias.includes(key)) return sector;
  }
  return key;
}
function curated(sector: string) {
  return SELECTED
    .filter((p) => !p.sector || String(p.sector).toLowerCase() === sector)
    .map((p, i) => ({
      id: String(p.id || `printful-selected-${i}`),
      sku: String(p.sku || ""),
      supplier: "Printful",
      provider: "printful",
      name: String(p.name || "Printful product"),
      category: String(p.category || sector),
      supplierPriceUsd: money(p.supplierPriceUsd) || money(p.suggestedRetailUsd),
      suggestedRetailUsd: money(p.suggestedRetailUsd) || money(p.supplierPriceUsd),
      image: String(p.image || ""),
      sector: String(p.sector || sector),
    }))
    .filter((p) => p.suggestedRetailUsd > 0 && p.name);
}
export async function onRequestGet(context: any) {
  const url = new URL(context.request.url);
  const wanted = url.searchParams.get("q") || url.searchParams.get("sector") || "";
  const defaultSector = String(SELECTED[0]?.sector || "beauty");
  const sector = resolveSector(wanted || defaultSector);
  const headers = { "access-control-allow-origin": "*", "cache-control": "public, max-age=60" };
  const products = curated(sector).slice(0, 50);
  return Response.json(
    { ok: true, supplier: "printful", sector, query: sector, products, count: products.length, source: "printful-selected-primary", markets: ["NO", "EU", "PE"] },
    { status: products.length ? 200 : 503, headers }
  );
}
